version: "2"

volumes:
  images:
  config:
  docker:

services:
  app:
    build: app
    privileged: true
    volumes:
      - images:/images
      - config:/root/.balena
      - docker:/var/lib/docker
    tmpfs:
      - /tmp
      - /var/run
      - /var/log
    cpu_shares: 896
  web:
    build: web
    ports:
      - 80:80/tcp
    volumes:
      - images:/images:ro
