version: "2"

volumes:
  images:
  config:
  docker:

services:
  preloader:
    build: .
    privileged: true
    volumes:
      - images:/images
      - config:/root/.balena
      - docker:/var/lib/docker
    tmpfs:
      - /tmp
      - /var/run
      - /var/log
    cpu_shares: 512
  web:
    build: web
    ports:
      - 80:80/tcp
    volumes:
      - images:/images:rw
    environment:
      - NGINX_USER=balena
      - NGINX_PASS=thespoonjumpsoverthemoon
