FROM klutchell/balena-cli:12.38.2

WORKDIR /usr/src/app

COPY preload.sh .

RUN chmod +x ./preload.sh

CMD [ "./preload.sh" ]

ENV DOWNLOAD_OS_VERSION latest
ENV PRELOAD_APP_RELEASE current
ENV CONFIG_NETWORK ethernet
ENV PRELOAD_APP_PINNED y
